var naming = "Hi! I'm Comfort Ngwenya";
console.log(naming);
var age = 28;
console.log(age);
var lesson = "Typescript exercise";
lesson = 2;
lesson = true;
console.log(lesson);
var value = "First lesson";
value = 1;
console.log(value);
